
export enum ViewType {
    LANDING = 'LANDING',
    DASHBOARD = 'DASHBOARD',
    LEADERBOARD = 'LEADERBOARD',
    RACE = 'RACE',
    ADMIN = 'ADMIN',
    REGISTER = 'REGISTER',
    MAINTENANCE = 'MAINTENANCE',
    MEMBER_BINDING = 'MEMBER_BINDING',
    AI_COACH = 'AI_COACH',
    TEAM_DASHBOARD = 'TEAM_DASHBOARD',
    MANAGER_DASHBOARD = 'MANAGER_DASHBOARD',
    SETTINGS = 'SETTINGS',
}

export enum RaceStatus {
    AWAITING = 'AWAITING',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED',
}
... [CONTENT TRUNCATED FOR THOUGHTFUL BATCHING] ...
